### ISSUE TITLE
Error in bokeh window

### ISSUE THREAD

**Issue by dpoursanidis** [jonm3D/OpenOceans#8]
(openoceans) D:\pythons\OpenOceans>bokeh serve --show manual_tool.py --websocket-max-message-size=300000000
2023-04-11 15:45:54,199 Starting Bokeh server version 3.1.0 (running on Tornado 6.2)
2023-04-11 15:45:54,542 Torndado websocket_max_message_size set to 300000000 bytes (286.10 MB)
2023-04-11 15:45:54,542 User authentication hooks NOT provided (default user enabled)
2023-04-11 15:45:54,547 Bokeh app running at: http://localhost:5006/manual_tool
2023-04-11 15:45:54,547 Starting Bokeh server with process id: 27540
2023-04-11 15:45:55,781 Error running application handler <bokeh.application.handlers.script.ScriptHandler object at 0x000001E505209BD0>: cannot import name 'Panel' from 'bokeh.models' (C:\Users\DimitrisPoursanidis\anaconda3\envs\openoceans\lib\site-packages\bokeh\models\__init__.py)
File 'manual_tool.py', line 31, in <module>:
from bokeh.models import Paragraph, Div, Panel, Tabs Traceback (most recent call last):
  File "C:\Users\DimitrisPoursanidis\anaconda3\envs\openoceans\lib\site-packages\bokeh\application\handlers\code_runner.py", line 231, in run
    exec(self._code, module.__dict__)
  File "D:\pythons\OpenOceans\manual_tool.py", line 31, in <module>
    from bokeh.models import Paragraph, Div, Panel, Tabs
ImportError: cannot import name 'Panel' from 'bokeh.models' (C:\Users\DimitrisPoursanidis\anaconda3\envs\openoceans\lib\site-packages\bokeh\models\__init__.py)

2023-04-11 15:45:56,057 WebSocket connection opened
2023-04-11 15:45:56,058 ServerConnection created

**Comment by liangyue2018** [comment]
A lower version for bokeh, e.g. 2.4.3
